Status =
    OMOTE: 0
    URA: 1
    MOTIGOMA: 2

FIRST = -1
SECOND = 1
COLS = 3
ROWS = 3
MAX_VALUE = 50000
MIN_VALUE = -50000
KIFU_ROW_LENGTH = 9
KIFU_ROW_LENGTH_SUB = 8
KIFU_KOMA_LENGTH = 3
TEMP_HISTORY = 'history.json'
TEMP_DUPLICATION = 'duplication.json'
LOADING_MESSAGE = 'Loading...'

module.exports =
    Status: Status
    FIRST: FIRST
    SECOND: SECOND
    COLS: COLS
    ROWS: ROWS
    MAX_VALUE: MAX_VALUE
    MIN_VALUE: MIN_VALUE
    KIFU_ROW_LENGTH: KIFU_ROW_LENGTH
    KIFU_ROW_LENGTH_SUB: KIFU_ROW_LENGTH_SUB
    KIFU_KOMA_LENGTH: KIFU_KOMA_LENGTH
    TEMP_HISTORY: TEMP_HISTORY
    TEMP_DUPLICATION: TEMP_DUPLICATION
    LOADING_MESSAGE: LOADING_MESSAGE
